### ISSUE TITLE
Error help link goes to invalid URL using Visual Studio Extension

### ISSUE THREAD

**Issue by eloisetaylor5693** [Microsoft/DevSkim-VisualStudio-Extension#11]
DevSkim issues link to [ds126858.md/](http://ds126858.md/) instead of [https://github.com/Microsoft/DevSkim/blob/master/guidance/DS126858.md](https://github.com/Microsoft/DevSkim/blob/master/guidance/DS126858.md) or other suitable location.

Using Visual Studio Extension version 0.3.1

Repro steps:
- Click on the help link in the Error List Window
OR 
- Right Click on the issue in the Error List Window
- Select _Show error help_

Hovering over the code, selecting Show Details does work, so just the other 2 methods noted above are not working as expected.

**Comment by PavelBansky** [comment]
Thank you for the report. Will fix it in next release
