### ISSUE TITLE
DevSkim keeps complaining about Temp.txt DS13713

### ISSUE THREAD

**Issue by BrianMinister** [Microsoft/DevSkim-VisualStudio-Extension#14]
Every time this comes up, I try to search for said Temp.txt file and cannot find it in side of my solution directory and my window's profile directory.

I don't store my projects off of my source folder from my windows profile directory, since file paths have a tendency to be long on legacy code. so my solution root is off of a root called c:\lcpcode\{repositoryName}\...

What am I missing on troubleshooting this? At the moment, I am having to disable the tool until I can find resolution.

**Comment by PavelBansky** [comment]
Hi,
thanks for your feedback. Are you referring to DevSkim for Visual Studio or Visual Studio Code?

Pavel
