### ISSUE TITLE
File Compare Tool in VS 2015 does not return comparing result

### ISSUE THREAD

**Issue by meialbert** [Microsoft/DevSkim-VisualStudio-Extension#17]
Running VS 2015 professional, with MS DevSkim installed and enabled

If file A is selected to "compare with latest version" in Team Explorer (using TFS), the compare window is open and the compare result never shows up when the file A is happen to opened in the VS.

If file A is not open in VS, compare result shows promptly.

If the MS DevSkim is disabled, there is no issue in the compare tool.

**Comment by gfs** [comment]
We no longer support VS 2015.
