### ISSUE TITLE
NuGet analyzer

### ISSUE THREAD

**Issue by clairernovotny** [Microsoft/DevSkim-VisualStudio-Extension#2]
Please release as an analyzer package via NuGet do we can use it without any install and have it run on CI servers as well.

**Comment by PavelBansky** [comment]
Working on it.

**Comment by PavelBansky** [comment]
The preview of the standalone analyzer is here:
https://github.com/Microsoft/DevSkim/tree/master/src/Microsoft.DevSkim

Unit Tests might give you idea, how things work until the documentation is ready:
https://github.com/Microsoft/DevSkim/blob/master/src/Microsoft.DevSkim/Microsoft.DevSkim.Tests/UseCaseTest.cs

Closing the issue for now

**Comment by jnm2** [comment]
This is especially important of OSS projects because it's a burden to ask contributors to install VS extensions just to contribute, to make sure they did install the extension, and to make sure they didn't miss anything. We'll be reviewing in a GitHub PR where your analyzer isn't running.
