### ISSUE TITLE
False Positive Warning

### ISSUE THREAD

**Issue by fourpastmidnight** [Microsoft/DevSkim-VisualStudio-Extension#6]
I had a comment in my code:

```
// TODO: Add ECB test
```

The term `ECB` is an acronym we use for one of the features of our application. This extension is flagging this as a potential security violation:

> **A weak cipher mode of operation was used**  
> **Severity: Important**  
> A potentially weak cipher mode of operation was used.  
> Fix Guidance: Consider using CBC, CTR, or GCM.

The acronym has nothing to do with encipherment. Maybe this extension should not be performing any matches on comments? OR, probably better, provide a way to turn off DevSkim warnings via a preprocessor directive (e.g. `#warning disable ...`) or special comment syntax like Resharper uses for selectively disabling some of its analyzers on a per-line/file/project basis.

**Comment by joshbw** [comment]
@scovetta - we could probably tighten the logic around the ECB rule (probably a good use for our new chained rule conditions - can check if it is being used in the context of crypto)

@PavelBansky - the other extensions don't flag findings in comments unless specifically told to.  Would be good to replicate that in VS.  Also, the other extensions have settings to disable specific rules, which we should probably replicate in the VS extension

**Comment by PavelBansky** [comment]
@joshbw : Some languages are using comments for code decoration attributes (like Java). Should such code be outside of DevSkim scope?

**Comment by fourpastmidnight** [comment]
@PavelBansky If DevSkim knows what language it's scanning, it would seem that whether or not to scan comments at all would start there. But once you are dealing with such a language, another mechanism must be able to help DevSkim out to know whether or not it should scan/report something.

This is perhaps where my suggestion about using a comment syntax like ReSharper or jshint/eslint and other hinters/linters use to "turn off and on" specific findings for a specific line/file/project may be a viable way to give DevSkim a hint.

**Comment by jnm2** [comment]
For C# at least it should ignore comments. What about string literals?

**Comment by gfs** [comment]
We now ignore comments so this issue is moot.
